# Generated by Django 5.2.17 on 2026-09-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_orderitem_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Storage key, e.g. products/2026/09/lamp.webp', max_length=255, unique=True)),
                ('content', models.BinaryField(help_text='Raw file bytes.')),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveIntegerField(default=0, help_text='Size in bytes.')),
                ('checksum', models.CharField(blank=True, default='', help_text='SHA-256 of the content; also used as the HTTP ETag.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media file',
                'verbose_name_plural': 'Media files',
                'ordering': ['name'],
            },
        ),
    ]
