# Generated by Django 5.2.17 on 2026-09-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the order was cancelled; empty while it is still live.', null=True),
        ),
    ]
